In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [6]:
arr[:4]

array([0, 1, 2, 3])

In [7]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [8]:
# In Numpy the data isn't copied to another variable
# So even if we do 
# slice = arr[4:7]
# slice[:] = 99
# the values of arr would still be changed
arr[4:7] = 99
arr

array([ 0,  1,  2,  3, 99, 99, 99,  7,  8,  9, 10])

In [10]:
# If you want a copy of the array
arr_copy = arr.copy()
arr_copy[2] = 666
print arr
print arr_copy

[ 0  1  2  3 99 99 99  7  8  9 10]
[  0   1 666   3  99  99  99   7   8   9  10]


In [11]:
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr_2d[1]

array([20, 25, 30])

In [12]:
arr_2d[2][1]

40

In [13]:
# 2D Array Slicing
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [14]:
arr2D = np.zeros((10,10))
arr2D

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
arr2D.shape

(10, 10)

In [18]:
for i in range(arr2D.shape[1]):
    arr2D[i] = i

In [19]:
arr2D

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [20]:
# Fancy indexing
arr2D[[2, 4, 6, 8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])