In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('myarr', arr)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.load('myarr.npy')

array([0, 1, 2, 3, 4])

In [7]:
arr1 = np.load('myarr.npy')
arr1

array([0, 1, 2, 3, 4])

In [8]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.savez('ziparray.npz', x = arr1, y = arr2)

In [10]:
archive_array = np.load('ziparray.npz')

In [11]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [12]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.savetxt('mytextarr.txt', arr, delimiter=',')

In [16]:
np.loadtxt('mytextarr.txt', delimiter=',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])