In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-0.35282973, -1.19889091,  0.76887603,  0.4822436 ,  0.59623667,
       -1.42916584,  1.69049759,  0.24373412, -0.61730749,  0.66029506])

In [7]:
B = np.random.randn(10)
B

array([ 0.29715202,  1.03311184,  0.41606112,  0.1910946 , -1.66643062,
       -1.89405179,  0.04154678,  1.91086686,  0.44010596,  0.63369604])

In [8]:
np.add(A, B)

array([-0.05567771, -0.16577907,  1.18493714,  0.6733382 , -1.07019394,
       -3.32321763,  1.73204437,  2.15460098, -0.17720153,  1.29399111])

In [9]:
np.maximum(A, B)

array([ 0.29715202,  1.03311184,  0.76887603,  0.4822436 ,  0.59623667,
       -1.42916584,  1.69049759,  1.91086686,  0.44010596,  0.66029506])

In [ ]:
# All binary functions for arrays are available at -
# https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#available-ufuncs