In [1]:
import numpy as np

In [3]:
my_list1 = [1, 2, 3, 4]
print my_list1

[1, 2, 3, 4]


In [4]:
my_array = np.array(my_list1)
print my_array

[1 2 3 4]


In [5]:
my_list2 = [11, 22, 33, 44]

In [7]:
my_lists = [my_list1, my_list2]
print my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]


In [8]:
my_array2 = np.array(my_lists)
print my_array2

[[ 1  2  3  4]
 [11 22 33 44]]


In [9]:
my_array2.shape

(2, 4)

In [10]:
my_array2.dtype

dtype('int64')

In [14]:
my_zeros_array = np.zeros(3)
my_zeros_array.dtype

dtype('float64')

In [16]:
my_ones_array = np.ones([5,5])
print my_ones_array

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [17]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [19]:
np.arange(2, 15, 3)

array([ 2,  5,  8, 11, 14])